language: node_js
node_js: '12'
sudo: enabled
dist: bionic
install:
  - npm ci
python:
  - 3.7
cache:
  directories:
    - node_modules
    - $HOME/.npm/_prebuilds
os:
  - linux
  - osx
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - ninja-build
      - libcurl4-openssl-dev
      - gtk+-3.0
      - wine-stable
      - pkg-config
      - mingw-w64
      - python3-pip
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ninja ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install meson ; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip3 install meson ; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=gcc-7 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-7 ; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "1" | sudo update-alternatives --config i686-w64-mingw32-g++ ; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./scripts/build-linux.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./scripts/build-darwin.sh ; fi
